kind = "web"
previewPath = "/"
title = "Credlyr"
version = "1.0.0"
id = "artifacts/credlyr"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25155

[services.development]
run = "pnpm --filter @workspace/credlyr run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/credlyr", "run", "build" ]
publicDir = "artifacts/credlyr/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25155"
BASE_PATH = "/"
